import Head from "next/head";
import { getAllPosts, getAllTags, getPostsForTopPage } from "lib/notionAPI";
import SinglePost from "components/Post/SinglePost";
import { GetStaticProps } from "next";
import Link from "next/link";
import Tag from "components/Tag/Tag";

export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getPostsForTopPage(4);
  const allTags = await getAllTags();

  return {
    props: {
      fourPosts,
      allTags,
    },
    //6時間ごとに更新60秒×60分×時間
    revalidate: 60 * 60 * 6,
  };
};

export default function Home({ fourPosts, allTags }: any) {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16"></main>
      <h1 className="text-5xl font-medium text-center mb-16">NotionでBlog🐴</h1>
      {fourPosts.map((post: any) => (
        <div className="mx-4" key={post.id}>
          <SinglePost
            title={post.title}
            description={post.description}
            date={post.date}
            tags={post.tags}
            slug={post.slug}
            isPaginationPage={false}
          />
        </div>
      ))}
      <Link
        href="/posts/page/1"
        className="block lg:w-1/2 mx-auto text-right text-lg font-medium p-3 pb-10 mt-3"
      >
        ...もっと見る
      </Link>
      <Tag tags={allTags} />
    </div>
  );
}
