import Head from "next/head";
import { getAllPosts } from "lib/notionAPI";
import SinglePost from "components/Post/SinglePost";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },
    //6時間ごとに更新60秒×60分×時間
    revalidate: 60 * 60 * 6,
  };
};

export default function Home({ allPosts }: any) {
  console.log(allPosts);
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16"></main>
      <h1 className="text-5xl font-medium text-center mb-16">NotionでBlog🐴</h1>
      {allPosts.map((post: any) => (
        <div className="mx-4">
          <SinglePost
            title={post.title}
            description={post.description}
            date={post.date}
            tags={post.tags}
            slug={post.slug}
          />
        </div>
      ))}
    </div>
  );
}
